## Viterbijev algoritam

In [3]:
y=np.array([1,2,3,4,5,5,6,6,6,6,6,6,1,2,3,4,5,2])
A = np.array([[0.9,0.1],[0.2,0.8]]) #2x2 matrica tranzicijska
A.shape
B = np.array([[0.166, 0.166, 0.166, 0.166, 0.166, 0.166 ],[0.100, 0.100, 0.100, 0.100, 0.100, 0.500]])
B.shape
#y.shape
A

array([[0.9, 0.1],
       [0.2, 0.8]])

In [2]:
import numpy as np

def viterbi2(y, A, B, initial_probs = None):
    K = A.shape[0]
    initial_probs = initial_probs if initial_probs is not None else np.full(K, 1 / K)
    T = len(y)
    T1 = np.empty((K, T), 'd')
    T2 = np.empty((K, T), 'B')
    T1[:, 0] = initial_probs * B[:, y[0]]
    T2[:, 0] = 0
    
    for i in range(1, T):
        T1[:, i] = np.max(T1[:, i - 1] * A.T * B[np.newaxis, :, y[i]].T, 1)
        T2[:, i] = np.argmax(T1[:, i - 1] * A.T, 1)

    x = np.empty(T, 'B')
    x[-1] = np.argmax(T1[:, T - 1])
    

    for i in reversed(range(1, T)):
        x[i - 1] = T2[x[i], i]

    return x, T1, T2

In [52]:
viterbi2(y,A,B)

IndexError: index 6 is out of bounds for axis 1 with size 6

In [8]:
import numpy as np

def my_viterbi(y, A, B):
    K = A.shape[0] #ovo je dva
    T = len(y) #ovo je 18
    T1 = np.empty((K, T), 'd') #2x18 neki arrayevi
    T2 = np.empty((K, T), 'B')
    T1[:, 0] =  B[:, y[0]]
    T2[:, 0] = 0
    
    for i in range(1, T):
        T1[:, i] = np.max(T1[:, i - 1] * A.T * B[np.newaxis, :, y[i]].T, 1)
        T2[:, i] = np.argmax(T1[:, i - 1] * A.T, 1)

    x = np.empty(T, 'B')
    x[-1] = np.argmax(T1[:, T - 1])
    

    for i in reversed(range(1, T)):
        x[i - 1] = T2[x[i], i]

    return x, T1, T2

In [11]:
 T1 = np.empty((2, 18), 'd')
T1[:, 0] =  B[:, y[0]]

In [13]:
T1.shape

(2, 18)

In [19]:
for i in range(1, 18):
        print(i)
        print(T1[:, i - 1] * A.T * B[np.newaxis, :, y[i]].T)
        T1[:, i] = np.max(T1[:, i - 1] * A.T * B[np.newaxis, :, y[i]].T, 1)
        print(T1[:,i])

1
[[0.0248004 0.00332  ]
 [0.00166   0.008    ]]
[0.0248004 0.008    ]
2
[[0.00370518 0.0002656 ]
 [0.000248   0.00064   ]]
[0.00370518 0.00064   ]
3
[[5.53553856e-04 2.12480000e-05]
 [3.70517976e-05 5.12000000e-05]]
[5.53553856e-04 5.12000000e-05]
4
[[8.27009461e-05 1.69984000e-06]
 [2.76776928e-05 2.04800000e-05]]
[8.27009461e-05 2.76776928e-05]
5
[[1.23555213e-05 9.18899401e-07]
 [4.13504731e-06 1.10710771e-05]]
[1.23555213e-05 1.10710771e-05]
6


IndexError: index 6 is out of bounds for axis 1 with size 6

In [20]:
A.T

array([[0.9, 0.2],
       [0.1, 0.8]])